// Standalone Mock Datasets for Standalone Cloud & Vercel Preview
import { Student, Hostel, Floor, Room, Bed, Allocation, FeeStructure, StudentFee, Payment, Attendance, LeaveRequest, Visitor, GatePass, Complaint, MaintenanceTask, MessMenu, Notice, User, AuditLog } from '../types';

export const MOCK_HOSTELS: Hostel[] = [
  {
    id: 'hostel-01',
    name: 'Aryabhatta Boys Hostel',
    code: 'ABH-01',
    type: 'BOYS',
    gender: 'MALE',
    address: 'North Campus, Engineering Block',
    capacity: 200,
    totalFloors: 3,
    totalRooms: 24,
    totalBeds: 52,
    occupiedBedsCount: 42,
    availableBedsCount: 10,
    occupancyRate: 80.7,
    status: 'ACTIVE',
    description: 'Primary residential hall for undergraduate male scholars with Wi-Fi and gymnasium.',
    warden: { id: 'user-warden-01', firstName: 'Prof. Robert', lastName: 'Langdon', email: 'warden.boys@hms.edu' },
  },
  {
    id: 'hostel-02',
    name: 'Gargi Girls Residence Hall',
    code: 'GGR-02',
    type: 'GIRLS',
    gender: 'FEMALE',
    address: 'South Campus, Academic Square',
    capacity: 180,
    totalFloors: 3,
    totalRooms: 18,
    totalBeds: 40,
    occupiedBedsCount: 32,
    availableBedsCount: 8,
    occupancyRate: 80.0,
    status: 'ACTIVE',
    description: 'Modern residential tower for female students with 24/7 CCTV surveillance and security.',
    warden: { id: 'user-warden-02', firstName: 'Dr. Sarah', lastName: 'Connor', email: 'warden.girls@hms.edu' },
  },
  {
    id: 'hostel-03',
    name: 'Ramanujan Postgraduate Block',
    code: 'RPG-03',
    type: 'CO_ED',
    gender: 'ALL',
    address: 'East Campus, Research Park',
    capacity: 100,
    totalFloors: 2,
    totalRooms: 12,
    totalBeds: 24,
    occupiedBedsCount: 18,
    availableBedsCount: 6,
    occupancyRate: 75.0,
    status: 'ACTIVE',
    description: 'Single and double occupancy block for M.Tech, MBA, and PhD research scholars.',
    warden: { id: 'user-warden-01', firstName: 'Prof. Robert', lastName: 'Langdon', email: 'warden.boys@hms.edu' },
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'stud-01',
    userId: 'user-stud-01',
    user: { id: 'user-stud-01', firstName: 'Aarav', lastName: 'Sharma', email: 'student@hms.edu', phone: '+91 98765 88990', isActive: true, avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024CS001',
    rollNo: '2024CS001',
    course: 'B.Tech',
    department: 'Computer Science',
    year: 3,
    semester: 6,
    gender: 'MALE',
    phone: '+91 98765 88990',
    email: 'student@hms.edu',
    bloodGroup: 'O+',
    admissionDate: '2023-08-01',
    emergencyContact: '+91 98765 00000',
    status: 'ACTIVE',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-02',
    userId: 'user-stud-02',
    user: { id: 'user-stud-02', firstName: 'Rohan', lastName: 'Verma', email: 'rohan.v@hms.edu', phone: '+91 98765 88991', isActive: true, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024IT014',
    rollNo: '2024IT014',
    course: 'B.Tech',
    department: 'Information Technology',
    year: 3,
    semester: 6,
    gender: 'MALE',
    phone: '+91 98765 88991',
    email: 'rohan.v@hms.edu',
    bloodGroup: 'B+',
    admissionDate: '2023-08-01',
    emergencyContact: '+91 98765 11111',
    status: 'ACTIVE',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-03',
    userId: 'user-stud-03',
    user: { id: 'user-stud-03', firstName: 'Ananya', lastName: 'Patel', email: 'ananya.p@hms.edu', phone: '+91 98765 88992', isActive: true, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024EC022',
    rollNo: '2024EC022',
    course: 'B.Tech',
    department: 'Electronics & Comm.',
    year: 2,
    semester: 4,
    gender: 'FEMALE',
    phone: '+91 98765 88992',
    email: 'ananya.p@hms.edu',
    bloodGroup: 'A+',
    admissionDate: '2024-08-01',
    emergencyContact: '+91 98765 22222',
    status: 'ACTIVE',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-04',
    userId: 'user-stud-04',
    user: { id: 'user-stud-04', firstName: 'Kavya', lastName: 'Iyer', email: 'kavya.i@hms.edu', phone: '+91 98765 88993', isActive: true, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024AI008',
    rollNo: '2024AI008',
    course: 'B.Tech',
    department: 'Artificial Intelligence',
    year: 2,
    semester: 4,
    gender: 'FEMALE',
    phone: '+91 98765 88993',
    email: 'kavya.i@hms.edu',
    bloodGroup: 'AB+',
    admissionDate: '2024-08-01',
    emergencyContact: '+91 98765 33333',
    status: 'ACTIVE',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-05',
    userId: 'user-stud-05',
    user: { id: 'user-stud-05', firstName: 'Vikram', lastName: 'Aditya', email: 'vikram.a@hms.edu', phone: '+91 98765 88994', isActive: true, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024ME035',
    rollNo: '2024ME035',
    course: 'B.Tech',
    department: 'Mechanical Engineering',
    year: 4,
    semester: 8,
    gender: 'MALE',
    phone: '+91 98765 88994',
    email: 'vikram.a@hms.edu',
    bloodGroup: 'O-',
    admissionDate: '2022-08-01',
    emergencyContact: '+91 98765 44444',
    status: 'ACTIVE',
    createdAt: '2022-08-01T00:00:00.000Z',
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-101',
    roomNumber: '101',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 2,
    feePerMonth: 5000,
    status: 'FULL',
    computedStatus: 'FULL',
    availableBeds: 0,
    amenities: 'Attached Bath, Study Table, Balcony',
    beds: [
      { id: 'bed-101-a', bedNumber: 'A', roomId: 'room-101', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[0] } as any] },
      { id: 'bed-101-b', bedNumber: 'B', roomId: 'room-101', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[1] } as any] },
    ],
  },
  {
    id: 'room-102',
    roomNumber: '102',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 1,
    feePerMonth: 5000,
    status: 'PARTIALLY_OCCUPIED',
    computedStatus: 'PARTIALLY_OCCUPIED',
    availableBeds: 1,
    amenities: 'Study Table, Ceiling Fan, Wardrobe',
    beds: [
      { id: 'bed-102-a', bedNumber: 'A', roomId: 'room-102', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[4] } as any] },
      { id: 'bed-102-b', bedNumber: 'B', roomId: 'room-102', status: 'AVAILABLE', allocations: [] },
    ],
  },
  {
    id: 'room-103',
    roomNumber: '103',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0 },
    type: 'SINGLE',
    capacity: 1,
    currentOccupancy: 0,
    feePerMonth: 8000,
    status: 'AVAILABLE',
    computedStatus: 'AVAILABLE',
    availableBeds: 1,
    amenities: 'Air Conditioned, High Speed LAN, Ergonomic Chair',
    beds: [
      { id: 'bed-103-a', bedNumber: 'A', roomId: 'room-103', status: 'AVAILABLE', allocations: [] },
    ],
  },
  {
    id: 'room-104',
    roomNumber: '104',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 0,
    feePerMonth: 5000,
    status: 'MAINTENANCE',
    computedStatus: 'MAINTENANCE',
    availableBeds: 0,
    amenities: 'Under Painting & Electrical Maintenance',
    beds: [
      { id: 'bed-104-a', bedNumber: 'A', roomId: 'room-104', status: 'MAINTENANCE', allocations: [] },
      { id: 'bed-104-b', bedNumber: 'B', roomId: 'room-104', status: 'MAINTENANCE', allocations: [] },
    ],
  },
  {
    id: 'room-201',
    roomNumber: '201',
    hostelId: 'hostel-02',
    hostel: { id: 'hostel-02', name: 'Gargi Girls Residence Hall', code: 'GGR-02' },
    floorId: 'floor-2',
    floor: { id: 'floor-2', name: '1st Floor', floorNumber: 1 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 2,
    feePerMonth: 5500,
    status: 'FULL',
    computedStatus: 'FULL',
    availableBeds: 0,
    amenities: 'Attached Balcony, Bookshelf, Mirror',
    beds: [
      { id: 'bed-201-a', bedNumber: 'A', roomId: 'room-201', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[2] } as any] },
      { id: 'bed-201-b', bedNumber: 'B', roomId: 'room-201', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[3] } as any] },
    ],
  },
];

export const MOCK_ALLOCATIONS: Allocation[] = [
  {
    id: 'alloc-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0, hostelId: 'hostel-01', totalRooms: 8, totalBeds: 16 },
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    bedId: 'bed-101-a',
    bed: { id: 'bed-101-a', bedNumber: 'A', roomId: 'room-101', status: 'OCCUPIED' },
    startDate: '2023-08-01',
    status: 'ACTIVE',
    remarks: 'Regular semester allotment',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'alloc-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    floorId: 'floor-1',
    floor: { id: 'floor-1', name: 'Ground Floor', floorNumber: 0, hostelId: 'hostel-01', totalRooms: 8, totalBeds: 16 },
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    bedId: 'bed-101-b',
    bed: { id: 'bed-101-b', bedNumber: 'B', roomId: 'room-101', status: 'OCCUPIED' },
    startDate: '2023-08-01',
    status: 'ACTIVE',
    remarks: 'Regular semester allotment',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'alloc-03',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    hostelId: 'hostel-02',
    hostel: MOCK_HOSTELS[1],
    floorId: 'floor-2',
    floor: { id: 'floor-2', name: '1st Floor', floorNumber: 1, hostelId: 'hostel-02', totalRooms: 8, totalBeds: 16 },
    roomId: 'room-201',
    room: MOCK_ROOMS[4],
    bedId: 'bed-201-a',
    bed: { id: 'bed-201-a', bedNumber: 'A', roomId: 'room-201', status: 'OCCUPIED' },
    startDate: '2024-08-01',
    status: 'ACTIVE',
    remarks: 'Girls residential allotment',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
];

export const MOCK_FEES: StudentFee[] = [
  {
    id: 'fee-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    feeStructureId: 'fs-01',
    feeStructure: {
      id: 'fs-01',
      name: 'Spring Semester 2026 Regular',
      hostelId: 'hostel-01',
      roomType: 'DOUBLE',
      academicYear: '2025-2026',
      semester: 6,
      hostelFee: 30000,
      messFee: 20000,
      maintenanceFee: 3000,
      securityDeposit: 5000,
      otherCharges: 1000,
      lateFeePerDay: 50,
      dueDate: '2026-03-31',
    },
    totalAmount: 59000,
    discountAmount: 0,
    paidAmount: 59000,
    balanceAmount: 0,
    dueDate: '2026-03-31',
    status: 'PAID',
  },
  {
    id: 'fee-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    feeStructureId: 'fs-01',
    feeStructure: {
      id: 'fs-01',
      name: 'Spring Semester 2026 Regular',
      hostelId: 'hostel-01',
      roomType: 'DOUBLE',
      academicYear: '2025-2026',
      semester: 6,
      hostelFee: 30000,
      messFee: 20000,
      maintenanceFee: 3000,
      securityDeposit: 5000,
      otherCharges: 1000,
      lateFeePerDay: 50,
      dueDate: '2026-03-31',
    },
    totalAmount: 59000,
    discountAmount: 0,
    paidAmount: 30000,
    balanceAmount: 29000,
    dueDate: '2026-03-31',
    status: 'PARTIALLY_PAID',
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-01',
    invoiceNo: 'HMS-REC-2026-001',
    studentFeeId: 'fee-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    amount: 59000,
    paymentMethod: 'UPI',
    transactionRef: 'UPI-992288334411',
    paymentDate: new Date().toISOString(),
    status: 'COMPLETED',
    remarks: 'Full Semester Fee Cleared via GPay',
  },
  {
    id: 'pay-02',
    invoiceNo: 'HMS-REC-2026-002',
    studentFeeId: 'fee-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    amount: 30000,
    paymentMethod: 'CARD',
    transactionRef: 'HDFC-TXN-882211',
    paymentDate: new Date().toISOString(),
    status: 'COMPLETED',
    remarks: 'Installment 1 Payment',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'comp-01',
    ticketNo: 'TICK-2026-081',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    category: 'ELECTRICAL',
    priority: 'HIGH',
    title: 'Bathroom Geyser not heating properly',
    description: 'The geyser in Room 101 ground floor bathroom has stopped heating water in the morning.',
    status: 'IN_PROGRESS',
    staffRemarks: 'Electrician dispatched to inspect heating element.',
    createdAt: new Date().toISOString(),
    comments: [
      { id: 'cm-1', complaintId: 'comp-01', userId: 'user-warden-01', user: { firstName: 'Robert', lastName: 'Langdon', role: 'WARDEN' }, message: 'Electrician assigned for 4:00 PM inspection.', createdAt: new Date().toISOString() },
    ],
  },
  {
    id: 'comp-02',
    ticketNo: 'TICK-2026-082',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    hostelId: 'hostel-02',
    hostel: MOCK_HOSTELS[1],
    category: 'INTERNET',
    priority: 'MEDIUM',
    title: 'Wi-Fi Access Point 2nd floor intermittent signal',
    description: 'High latency and packet drops on 5GHz Wi-Fi in the study hall.',
    status: 'RESOLVED',
    staffRemarks: 'Router rebooted and channel frequency tuned.',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_GATE_PASSES: GatePass[] = [
  {
    id: 'gp-01',
    passNumber: 'GP-2026-092',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    purpose: 'Academic Project Component Purchase',
    destination: 'City Electronics Market',
    departureDate: new Date().toISOString().split('T')[0],
    departureTime: '17:30',
    expectedReturnDate: new Date().toISOString().split('T')[0],
    expectedReturnTime: '21:00',
    status: 'ACTIVE',
    qrCode: 'GP-QR-2026092-AARAV',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'gp-02',
    passNumber: 'GP-2026-093',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    purpose: 'Weekend Home Visit',
    destination: 'Hometown Residence',
    departureDate: new Date().toISOString().split('T')[0],
    departureTime: '18:00',
    expectedReturnDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    expectedReturnTime: '20:00',
    status: 'APPROVED',
    qrCode: 'GP-QR-2026093-ROHAN',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_NOTICES: Notice[] = [
  {
    id: 'not-01',
    title: 'Annual Hostel Cultural Night & Dinner Gala',
    content: 'All residents of Aryabhatta, Gargi, and Ramanujan hostels are cordially invited to the Annual Cultural Evening on Saturday at 7:00 PM in the Central Amphitheatre.',
    category: 'EVENT',
    priority: 'HIGH',
    targetAudience: 'ALL',
    isPinned: true,
    publishDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'not-02',
    title: 'Spring Semester Fee Clearance Deadline Reminder',
    content: 'Scholars with outstanding balances are requested to clear their semester dues before the 31st of this month to ensure uninterrupted room allotment and mess privileges.',
    category: 'GENERAL',
    priority: 'NORMAL',
    targetAudience: 'HOSTEL',
    isPinned: false,
    publishDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];
