// Standalone Mock Datasets for Standalone Cloud & Vercel Preview
import { Student, Hostel, Floor, Room, Bed, Allocation, FeeStructure, StudentFee, Payment, Attendance, LeaveRequest, Visitor, GatePass, Complaint, MaintenanceTask, MessMenu, Notice, User, AuditLog, Guardian } from '../types';

export const MOCK_HOSTELS: Hostel[] = [
  {
    id: 'hostel-01',
    name: 'Aryabhatta Boys Hostel',
    code: 'ABH-01',
    type: 'BOYS',
    gender: 'MALE',
    address: 'North Campus, Engineering Block',
    capacity: 200,
    totalFloors: 3,
    totalRooms: 24,
    totalBeds: 52,
    occupiedBedsCount: 42,
    availableBedsCount: 10,
    occupancyRate: 80.7,
    status: 'ACTIVE',
    description: 'Primary residential hall for undergraduate male scholars with Wi-Fi and gymnasium.',
    warden: { id: 'user-warden-01', firstName: 'Prof. Robert', lastName: 'Langdon', email: 'warden.boys@hms.edu' },
  },
  {
    id: 'hostel-02',
    name: 'Gargi Girls Residence Hall',
    code: 'GGR-02',
    type: 'GIRLS',
    gender: 'FEMALE',
    address: 'South Campus, Academic Square',
    capacity: 180,
    totalFloors: 3,
    totalRooms: 18,
    totalBeds: 40,
    occupiedBedsCount: 32,
    availableBedsCount: 8,
    occupancyRate: 80.0,
    status: 'ACTIVE',
    description: 'Modern residential tower for female students with 24/7 CCTV surveillance and security.',
    warden: { id: 'user-warden-02', firstName: 'Dr. Sarah', lastName: 'Connor', email: 'warden.girls@hms.edu' },
  },
  {
    id: 'hostel-03',
    name: 'Ramanujan Postgraduate Block',
    code: 'RPG-03',
    type: 'CO_ED',
    gender: 'ALL',
    address: 'East Campus, Research Park',
    capacity: 100,
    totalFloors: 2,
    totalRooms: 12,
    totalBeds: 24,
    occupiedBedsCount: 18,
    availableBedsCount: 6,
    occupancyRate: 75.0,
    status: 'ACTIVE',
    description: 'Single and double occupancy block for M.Tech, MBA, and PhD research scholars.',
    warden: { id: 'user-warden-01', firstName: 'Prof. Robert', lastName: 'Langdon', email: 'warden.boys@hms.edu' },
  },
];

export const MOCK_FLOORS: Floor[] = [
  { id: 'floor-01', floorNumber: 0, name: 'Ground Floor (Level 0)', hostelId: 'hostel-01', hostel: { name: 'Aryabhatta Boys Hostel', code: 'ABH-01' }, totalRooms: 8, totalBeds: 16 },
  { id: 'floor-02', floorNumber: 1, name: 'First Floor (Level 1)', hostelId: 'hostel-01', hostel: { name: 'Aryabhatta Boys Hostel', code: 'ABH-01' }, totalRooms: 8, totalBeds: 18 },
  { id: 'floor-03', floorNumber: 2, name: 'Second Floor (Level 2)', hostelId: 'hostel-01', hostel: { name: 'Aryabhatta Boys Hostel', code: 'ABH-01' }, totalRooms: 8, totalBeds: 18 },
  { id: 'floor-04', floorNumber: 0, name: 'Ground Floor (Level 0)', hostelId: 'hostel-02', hostel: { name: 'Gargi Girls Residence Hall', code: 'GGR-02' }, totalRooms: 6, totalBeds: 12 },
  { id: 'floor-05', floorNumber: 1, name: 'First Floor (Level 1)', hostelId: 'hostel-02', hostel: { name: 'Gargi Girls Residence Hall', code: 'GGR-02' }, totalRooms: 6, totalBeds: 14 },
  { id: 'floor-06', floorNumber: 0, name: 'Ground Floor (Level 0)', hostelId: 'hostel-03', hostel: { name: 'Ramanujan Postgraduate Block', code: 'RPG-03' }, totalRooms: 6, totalBeds: 12 },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'stud-01',
    userId: 'user-stud-01',
    user: { id: 'user-stud-01', firstName: 'Aarav', lastName: 'Sharma', email: 'student@hms.edu', phone: '+91 98765 88990', isActive: true, avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024CS001',
    rollNo: '2024CS001',
    course: 'B.Tech',
    department: 'Computer Science',
    year: 3,
    semester: 6,
    gender: 'MALE',
    phone: '+91 98765 88990',
    email: 'student@hms.edu',
    bloodGroup: 'O+',
    admissionDate: '2023-08-01',
    emergencyContact: '+91 98765 00000',
    status: 'ACTIVE',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-02',
    userId: 'user-stud-02',
    user: { id: 'user-stud-02', firstName: 'Rohan', lastName: 'Verma', email: 'rohan.v@hms.edu', phone: '+91 98765 88991', isActive: true, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024IT014',
    rollNo: '2024IT014',
    course: 'B.Tech',
    department: 'Information Technology',
    year: 3,
    semester: 6,
    gender: 'MALE',
    phone: '+91 98765 88991',
    email: 'rohan.v@hms.edu',
    bloodGroup: 'B+',
    admissionDate: '2023-08-01',
    emergencyContact: '+91 98765 11111',
    status: 'ACTIVE',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-03',
    userId: 'user-stud-03',
    user: { id: 'user-stud-03', firstName: 'Ananya', lastName: 'Patel', email: 'ananya.p@hms.edu', phone: '+91 98765 88992', isActive: true, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024EC022',
    rollNo: '2024EC022',
    course: 'B.Tech',
    department: 'Electronics & Comm.',
    year: 2,
    semester: 4,
    gender: 'FEMALE',
    phone: '+91 98765 88992',
    email: 'ananya.p@hms.edu',
    bloodGroup: 'A+',
    admissionDate: '2024-08-01',
    emergencyContact: '+91 98765 22222',
    status: 'ACTIVE',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-04',
    userId: 'user-stud-04',
    user: { id: 'user-stud-04', firstName: 'Kavya', lastName: 'Iyer', email: 'kavya.i@hms.edu', phone: '+91 98765 88993', isActive: true, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024AI008',
    rollNo: '2024AI008',
    course: 'B.Tech',
    department: 'Artificial Intelligence',
    year: 2,
    semester: 4,
    gender: 'FEMALE',
    phone: '+91 98765 88993',
    email: 'kavya.i@hms.edu',
    bloodGroup: 'AB+',
    admissionDate: '2024-08-01',
    emergencyContact: '+91 98765 33333',
    status: 'ACTIVE',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'stud-05',
    userId: 'user-stud-05',
    user: { id: 'user-stud-05', firstName: 'Vikram', lastName: 'Aditya', email: 'vikram.a@hms.edu', phone: '+91 98765 88994', isActive: true, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80' },
    enrollmentNo: 'EN2024ME035',
    rollNo: '2024ME035',
    course: 'B.Tech',
    department: 'Mechanical Engineering',
    year: 4,
    semester: 8,
    gender: 'MALE',
    phone: '+91 98765 88994',
    email: 'vikram.a@hms.edu',
    bloodGroup: 'O-',
    admissionDate: '2022-08-01',
    emergencyContact: '+91 98765 44444',
    status: 'ACTIVE',
    createdAt: '2022-08-01T00:00:00.000Z',
  },
];

export const MOCK_GUARDIANS: Guardian[] = [
  {
    id: 'guard-01',
    name: 'Rajesh Sharma',
    relation: 'Father',
    phone: '+91 98765 99001',
    email: 'rajesh.sharma@gmail.com',
    occupation: 'Senior Civil Engineer',
    address: 'Flat 402, Green Park Avenue, New Delhi',
    students: [{ student: MOCK_STUDENTS[0] }],
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'guard-02',
    name: 'Sunita Verma',
    relation: 'Mother',
    phone: '+91 98765 99002',
    email: 'sunita.verma@yahoo.com',
    occupation: 'Professor of Mathematics',
    address: 'B-12, Sector 15, Chandigarh',
    students: [{ student: MOCK_STUDENTS[1] }],
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'guard-03',
    name: 'Dr. Ramesh Patel',
    relation: 'Father',
    phone: '+91 98765 99003',
    email: 'dr.patel@clinic.org',
    occupation: 'Chief Medical Officer',
    address: '77 Heritage Heights, Ahmedabad',
    students: [{ student: MOCK_STUDENTS[2] }],
    createdAt: '2024-08-01T00:00:00.000Z',
  },
  {
    id: 'guard-04',
    name: 'Meenakshi Iyer',
    relation: 'Mother',
    phone: '+91 98765 99004',
    email: 'meenakshi.iyer@tcs.com',
    occupation: 'Software Enterprise Architect',
    address: 'Plot 88, Anna Nagar, Chennai',
    students: [{ student: MOCK_STUDENTS[3] }],
    createdAt: '2024-08-01T00:00:00.000Z',
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-101',
    roomNumber: '101',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-01',
    floor: { id: 'floor-01', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 2,
    feePerMonth: 5000,
    status: 'FULL',
    computedStatus: 'FULL',
    availableBeds: 0,
    amenities: 'Attached Bath, Study Table, Balcony',
    beds: [
      { id: 'bed-101-a', bedNumber: 'A', roomId: 'room-101', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[0] } as any] },
      { id: 'bed-101-b', bedNumber: 'B', roomId: 'room-101', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[1] } as any] },
    ],
  },
  {
    id: 'room-102',
    roomNumber: '102',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-01',
    floor: { id: 'floor-01', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 1,
    feePerMonth: 5000,
    status: 'PARTIALLY_OCCUPIED',
    computedStatus: 'PARTIALLY_OCCUPIED',
    availableBeds: 1,
    amenities: 'Study Table, Ceiling Fan, Wardrobe',
    beds: [
      { id: 'bed-102-a', bedNumber: 'A', roomId: 'room-102', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[4] } as any] },
      { id: 'bed-102-b', bedNumber: 'B', roomId: 'room-102', status: 'AVAILABLE', allocations: [] },
    ],
  },
  {
    id: 'room-103',
    roomNumber: '103',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-01',
    floor: { id: 'floor-01', name: 'Ground Floor', floorNumber: 0 },
    type: 'SINGLE',
    capacity: 1,
    currentOccupancy: 0,
    feePerMonth: 8000,
    status: 'AVAILABLE',
    computedStatus: 'AVAILABLE',
    availableBeds: 1,
    amenities: 'Air Conditioned, High Speed LAN, Ergonomic Chair',
    beds: [
      { id: 'bed-103-a', bedNumber: 'A', roomId: 'room-103', status: 'AVAILABLE', allocations: [] },
    ],
  },
  {
    id: 'room-104',
    roomNumber: '104',
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel', code: 'ABH-01' },
    floorId: 'floor-01',
    floor: { id: 'floor-01', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 0,
    feePerMonth: 5000,
    status: 'MAINTENANCE',
    computedStatus: 'MAINTENANCE',
    availableBeds: 0,
    amenities: 'Under Painting & Electrical Maintenance',
    beds: [
      { id: 'bed-104-a', bedNumber: 'A', roomId: 'room-104', status: 'MAINTENANCE', allocations: [] },
      { id: 'bed-104-b', bedNumber: 'B', roomId: 'room-104', status: 'MAINTENANCE', allocations: [] },
    ],
  },
  {
    id: 'room-201',
    roomNumber: '201',
    hostelId: 'hostel-02',
    hostel: { id: 'hostel-02', name: 'Gargi Girls Residence Hall', code: 'GGR-02' },
    floorId: 'floor-04',
    floor: { id: 'floor-04', name: 'Ground Floor', floorNumber: 0 },
    type: 'DOUBLE',
    capacity: 2,
    currentOccupancy: 2,
    feePerMonth: 5500,
    status: 'FULL',
    computedStatus: 'FULL',
    availableBeds: 0,
    amenities: 'Attached Balcony, Bookshelf, Mirror',
    beds: [
      { id: 'bed-201-a', bedNumber: 'A', roomId: 'room-201', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[2] } as any] },
      { id: 'bed-201-b', bedNumber: 'B', roomId: 'room-201', status: 'OCCUPIED', allocations: [{ student: MOCK_STUDENTS[3] } as any] },
    ],
  },
];

export const MOCK_BEDS: Bed[] = [
  { id: 'bed-101-a', bedNumber: '101-A', roomId: 'room-101', status: 'OCCUPIED', room: MOCK_ROOMS[0], allocations: [{ student: MOCK_STUDENTS[0] } as any] },
  { id: 'bed-101-b', bedNumber: '101-B', roomId: 'room-101', status: 'OCCUPIED', room: MOCK_ROOMS[0], allocations: [{ student: MOCK_STUDENTS[1] } as any] },
  { id: 'bed-102-a', bedNumber: '102-A', roomId: 'room-102', status: 'OCCUPIED', room: MOCK_ROOMS[1], allocations: [{ student: MOCK_STUDENTS[4] } as any] },
  { id: 'bed-102-b', bedNumber: '102-B', roomId: 'room-102', status: 'AVAILABLE', room: MOCK_ROOMS[1], allocations: [] },
  { id: 'bed-103-a', bedNumber: '103-A', roomId: 'room-103', status: 'AVAILABLE', room: MOCK_ROOMS[2], allocations: [] },
  { id: 'bed-104-a', bedNumber: '104-A', roomId: 'room-104', status: 'MAINTENANCE', room: MOCK_ROOMS[3], allocations: [] },
  { id: 'bed-104-b', bedNumber: '104-B', roomId: 'room-104', status: 'MAINTENANCE', room: MOCK_ROOMS[3], allocations: [] },
  { id: 'bed-201-a', bedNumber: '201-A', roomId: 'room-201', status: 'OCCUPIED', room: MOCK_ROOMS[4], allocations: [{ student: MOCK_STUDENTS[2] } as any] },
  { id: 'bed-201-b', bedNumber: '201-B', roomId: 'room-201', status: 'OCCUPIED', room: MOCK_ROOMS[4], allocations: [{ student: MOCK_STUDENTS[3] } as any] },
];

export const MOCK_ALLOCATIONS: Allocation[] = [
  {
    id: 'alloc-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    floorId: 'floor-01',
    floor: MOCK_FLOORS[0],
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    bedId: 'bed-101-a',
    bed: MOCK_BEDS[0],
    startDate: '2023-08-01',
    status: 'ACTIVE',
    remarks: 'Regular semester allotment',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'alloc-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    floorId: 'floor-01',
    floor: MOCK_FLOORS[0],
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    bedId: 'bed-101-b',
    bed: MOCK_BEDS[1],
    startDate: '2023-08-01',
    status: 'ACTIVE',
    remarks: 'Regular semester allotment',
    createdAt: '2023-08-01T00:00:00.000Z',
  },
  {
    id: 'alloc-03',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    hostelId: 'hostel-02',
    hostel: MOCK_HOSTELS[1],
    floorId: 'floor-04',
    floor: MOCK_FLOORS[3],
    roomId: 'room-201',
    room: MOCK_ROOMS[4],
    bedId: 'bed-201-a',
    bed: MOCK_BEDS[7],
    startDate: '2024-08-01',
    status: 'ACTIVE',
    remarks: 'Girls residential allotment',
    createdAt: '2024-08-01T00:00:00.000Z',
  },
];

export const MOCK_ATTENDANCE: Attendance[] = [
  {
    id: 'att-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    studentName: 'Aarav Sharma',
    enrollmentNo: 'EN2024CS001',
    roomNumber: '101',
    bedNumber: 'A',
    floorName: 'Ground Floor',
    hostelId: 'hostel-01',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    checkInTime: '21:15',
    remarks: 'Biometric verified at entry gate',
  },
  {
    id: 'att-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    studentName: 'Rohan Verma',
    enrollmentNo: 'EN2024IT014',
    roomNumber: '101',
    bedNumber: 'B',
    floorName: 'Ground Floor',
    hostelId: 'hostel-01',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    checkInTime: '21:30',
    remarks: 'Verified during floor roll call',
  },
  {
    id: 'att-03',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    studentName: 'Ananya Patel',
    enrollmentNo: 'EN2024EC022',
    roomNumber: '201',
    bedNumber: 'A',
    floorName: '1st Floor',
    hostelId: 'hostel-02',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    checkInTime: '20:45',
    remarks: 'Present in residence hall',
  },
  {
    id: 'att-04',
    studentId: 'stud-04',
    student: MOCK_STUDENTS[3],
    studentName: 'Kavya Iyer',
    enrollmentNo: 'EN2024AI008',
    roomNumber: '201',
    bedNumber: 'B',
    floorName: '1st Floor',
    hostelId: 'hostel-02',
    date: new Date().toISOString().split('T')[0],
    status: 'LEAVE',
    remarks: 'Approved home leave until Monday',
  },
  {
    id: 'att-05',
    studentId: 'stud-05',
    student: MOCK_STUDENTS[4],
    studentName: 'Vikram Aditya',
    enrollmentNo: 'EN2024ME035',
    roomNumber: '102',
    bedNumber: 'A',
    floorName: 'Ground Floor',
    hostelId: 'hostel-01',
    date: new Date().toISOString().split('T')[0],
    status: 'LATE',
    checkInTime: '22:40',
    remarks: 'Late check-in recorded at security desk',
  },
];

export const MOCK_LEAVES: LeaveRequest[] = [
  {
    id: 'leave-01',
    studentId: 'stud-04',
    student: MOCK_STUDENTS[3],
    leaveType: 'HOME_VISIT',
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    reason: 'Family wedding ceremony in hometown',
    emergencyPhone: '+91 98765 33333',
    parentPhone: '+91 98765 99004',
    status: 'APPROVED',
    wardenRemarks: 'Parent confirmed via phone call. Outing permitted.',
    approvedBy: { firstName: 'Dr. Sarah', lastName: 'Connor' },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'leave-02',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    leaveType: 'ACADEMIC',
    startDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    endDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    reason: 'Participating in National Hackathon at IIT Bombay',
    emergencyPhone: '+91 98765 00000',
    parentPhone: '+91 98765 99001',
    status: 'PENDING',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'leave-03',
    studentId: 'stud-05',
    student: MOCK_STUDENTS[4],
    leaveType: 'MEDICAL',
    startDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    endDate: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    reason: 'Doctor prescribed rest for viral fever',
    status: 'APPROVED',
    wardenRemarks: 'Medical certificate verified.',
    approvedBy: { firstName: 'Prof. Robert', lastName: 'Langdon' },
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const MOCK_VISITORS: Visitor[] = [
  {
    id: 'vis-01',
    visitorName: 'Rajesh Sharma',
    phone: '+91 98765 99001',
    relation: 'Father',
    idProofType: 'Aadhaar Card',
    idProofNumber: 'XXXX-XXXX-4819',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    purpose: 'Deliver academic textbooks and stationery',
    checkInTime: new Date(Date.now() - 7200000).toISOString(),
    status: 'INSIDE',
    securityStaff: { firstName: 'Marcus', lastName: 'Fenix' },
    remarks: 'Visitor badge #04 issued',
  },
  {
    id: 'vis-02',
    visitorName: 'Dr. Ramesh Patel',
    phone: '+91 98765 99003',
    relation: 'Father',
    idProofType: 'Driving License',
    idProofNumber: 'DL-04201900182',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    purpose: 'Monthly family visit and semester check-in',
    checkInTime: new Date(Date.now() - 14400000).toISOString(),
    checkOutTime: new Date(Date.now() - 3600000).toISOString(),
    status: 'CHECKED_OUT',
    securityStaff: { firstName: 'Marcus', lastName: 'Fenix' },
    remarks: 'Checked out safely at main gate',
  },
];

export const MOCK_MAINTENANCE: MaintenanceTask[] = [
  {
    id: 'maint-01',
    taskNumber: 'MNT-2026-041',
    complaintId: 'comp-01',
    complaint: { id: 'comp-01', ticketNo: 'TICK-2026-081', title: 'Bathroom Geyser not heating properly' },
    hostelId: 'hostel-01',
    hostel: { id: 'hostel-01', name: 'Aryabhatta Boys Hostel' },
    roomId: 'room-101',
    room: { id: 'room-101', roomNumber: '101' },
    title: 'Replace 25L Heating Element & Thermostat',
    description: 'Electrician dispatched with spare heating coil and wiring connectors.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedTo: { id: 'user-maint-01', firstName: 'Bob', lastName: 'Builder', phone: '+91 98765 77889', email: 'maintenance@hms.edu' },
    estimatedCost: 1200,
    actualCost: 1150,
    estimatedCompletion: 'Today, 5:30 PM',
    notes: 'Parts requisition approved by warden.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'maint-02',
    taskNumber: 'MNT-2026-042',
    hostelId: 'hostel-02',
    hostel: { id: 'hostel-02', name: 'Gargi Girls Residence Hall' },
    roomId: 'room-201',
    room: { id: 'room-201', roomNumber: '201' },
    title: 'Study Table Drawer Lock Replacement',
    description: 'Carpentry repair for sliding lock mechanism.',
    priority: 'LOW',
    status: 'COMPLETED',
    assignedTo: { id: 'user-maint-01', firstName: 'Bob', lastName: 'Builder', phone: '+91 98765 77889', email: 'maintenance@hms.edu' },
    estimatedCost: 350,
    actualCost: 300,
    actualCompletion: new Date().toISOString(),
    notes: 'Key handed over to student resident.',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const MOCK_MESS_MENUS: MessMenu[] = [
  { id: 'mess-01', hostelId: 'hostel-01', dayOfWeek: 'MONDAY', mealType: 'BREAKFAST', items: 'Masala Dosa, Sambar, Coconut Chutney, Boiled Eggs, Tea / Coffee', specialItem: 'Filter Coffee', calorieCount: 520, isActive: true },
  { id: 'mess-02', hostelId: 'hostel-01', dayOfWeek: 'MONDAY', mealType: 'LUNCH', items: 'Shahi Paneer / Chicken Curry, Dal Tadka, Jeera Rice, Phulka Roti, Salad', specialItem: 'Gulab Jamun', calorieCount: 780, isActive: true },
  { id: 'mess-03', hostelId: 'hostel-01', dayOfWeek: 'MONDAY', mealType: 'SNACKS', items: 'Veg Cutlet, Green Mint Chutney, Hot Masala Tea / Milk', calorieCount: 280, isActive: true },
  { id: 'mess-04', hostelId: 'hostel-01', dayOfWeek: 'MONDAY', mealType: 'DINNER', items: 'Dum Aloo, Mix Dal Makhani, Steamed Rice, Tandoori Roti, Raita', specialItem: 'Ice Cream', calorieCount: 690, isActive: true },
  { id: 'mess-05', hostelId: 'hostel-01', dayOfWeek: 'TUESDAY', mealType: 'BREAKFAST', items: 'Aloo Paratha with Curd, Boiled Sprouts, Seasonal Fruits, Milk', calorieCount: 540, isActive: true },
  { id: 'mess-06', hostelId: 'hostel-01', dayOfWeek: 'TUESDAY', mealType: 'LUNCH', items: 'Rajma Masala, Steamed Basmati Rice, Chapati, Boondi Raita, Papad', calorieCount: 720, isActive: true },
];

export const MOCK_FEES: StudentFee[] = [
  {
    id: 'fee-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    feeStructureId: 'fs-01',
    feeStructure: {
      id: 'fs-01',
      name: 'Spring Semester 2026 Regular',
      hostelId: 'hostel-01',
      roomType: 'DOUBLE',
      academicYear: '2025-2026',
      semester: 6,
      hostelFee: 30000,
      messFee: 20000,
      maintenanceFee: 3000,
      securityDeposit: 5000,
      otherCharges: 1000,
      lateFeePerDay: 50,
      dueDate: '2026-03-31',
    },
    totalAmount: 59000,
    discountAmount: 0,
    paidAmount: 59000,
    balanceAmount: 0,
    dueDate: '2026-03-31',
    status: 'PAID',
  },
  {
    id: 'fee-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    feeStructureId: 'fs-01',
    feeStructure: {
      id: 'fs-01',
      name: 'Spring Semester 2026 Regular',
      hostelId: 'hostel-01',
      roomType: 'DOUBLE',
      academicYear: '2025-2026',
      semester: 6,
      hostelFee: 30000,
      messFee: 20000,
      maintenanceFee: 3000,
      securityDeposit: 5000,
      otherCharges: 1000,
      lateFeePerDay: 50,
      dueDate: '2026-03-31',
    },
    totalAmount: 59000,
    discountAmount: 0,
    paidAmount: 30000,
    balanceAmount: 29000,
    dueDate: '2026-03-31',
    status: 'PARTIALLY_PAID',
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-01',
    invoiceNo: 'HMS-REC-2026-001',
    studentFeeId: 'fee-01',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    amount: 59000,
    paymentMethod: 'UPI',
    transactionRef: 'UPI-992288334411',
    paymentDate: new Date().toISOString(),
    status: 'COMPLETED',
    remarks: 'Full Semester Fee Cleared via GPay',
  },
  {
    id: 'pay-02',
    invoiceNo: 'HMS-REC-2026-002',
    studentFeeId: 'fee-02',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    amount: 30000,
    paymentMethod: 'CARD',
    transactionRef: 'HDFC-TXN-882211',
    paymentDate: new Date().toISOString(),
    status: 'COMPLETED',
    remarks: 'Installment 1 Payment',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'comp-01',
    ticketNo: 'TICK-2026-081',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    hostelId: 'hostel-01',
    hostel: MOCK_HOSTELS[0],
    roomId: 'room-101',
    room: MOCK_ROOMS[0],
    category: 'ELECTRICAL',
    priority: 'HIGH',
    title: 'Bathroom Geyser not heating properly',
    description: 'The geyser in Room 101 ground floor bathroom has stopped heating water in the morning.',
    status: 'IN_PROGRESS',
    staffRemarks: 'Electrician dispatched to inspect heating element.',
    createdAt: new Date().toISOString(),
    comments: [
      { id: 'cm-1', complaintId: 'comp-01', userId: 'user-warden-01', user: { firstName: 'Robert', lastName: 'Langdon', role: 'WARDEN' }, message: 'Electrician assigned for 4:00 PM inspection.', createdAt: new Date().toISOString() },
    ],
  },
  {
    id: 'comp-02',
    ticketNo: 'TICK-2026-082',
    studentId: 'stud-03',
    student: MOCK_STUDENTS[2],
    hostelId: 'hostel-02',
    hostel: MOCK_HOSTELS[1],
    category: 'INTERNET',
    priority: 'MEDIUM',
    title: 'Wi-Fi Access Point 2nd floor intermittent signal',
    description: 'High latency and packet drops on 5GHz Wi-Fi in the study hall.',
    status: 'RESOLVED',
    staffRemarks: 'Router rebooted and channel frequency tuned.',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_GATE_PASSES: GatePass[] = [
  {
    id: 'gp-01',
    passNumber: 'GP-2026-092',
    studentId: 'stud-01',
    student: MOCK_STUDENTS[0],
    purpose: 'Academic Project Component Purchase',
    destination: 'City Electronics Market',
    departureDate: new Date().toISOString().split('T')[0],
    departureTime: '17:30',
    expectedReturnDate: new Date().toISOString().split('T')[0],
    expectedReturnTime: '21:00',
    status: 'ACTIVE',
    qrCode: 'GP-QR-2026092-AARAV',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'gp-02',
    passNumber: 'GP-2026-093',
    studentId: 'stud-02',
    student: MOCK_STUDENTS[1],
    purpose: 'Weekend Home Visit',
    destination: 'Hometown Residence',
    departureDate: new Date().toISOString().split('T')[0],
    departureTime: '18:00',
    expectedReturnDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    expectedReturnTime: '20:00',
    status: 'APPROVED',
    qrCode: 'GP-QR-2026093-ROHAN',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_NOTICES: Notice[] = [
  {
    id: 'not-01',
    title: 'Annual Hostel Cultural Night & Dinner Gala',
    content: 'All residents of Aryabhatta, Gargi, and Ramanujan hostels are cordially invited to the Annual Cultural Evening on Saturday at 7:00 PM in the Central Amphitheatre.',
    category: 'EVENT',
    priority: 'HIGH',
    targetAudience: 'ALL',
    isPinned: true,
    publishDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'not-02',
    title: 'Spring Semester Fee Clearance Deadline Reminder',
    content: 'Scholars with outstanding balances are requested to clear their semester dues before the 31st of this month to ensure uninterrupted room allotment and mess privileges.',
    category: 'GENERAL',
    priority: 'NORMAL',
    targetAudience: 'HOSTEL',
    isPinned: false,
    publishDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_USERS_LIST: User[] = [
  { id: 'user-01', email: 'superadmin@hms.edu', firstName: 'Alexander', lastName: 'Vance', role: 'SUPER_ADMIN', isActive: true, phone: '+91 98765 43210', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-02', email: 'admin@hms.edu', firstName: 'Eleanor', lastName: 'Rigby', role: 'ADMIN', isActive: true, phone: '+91 98765 11223', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-03', email: 'warden.boys@hms.edu', firstName: 'Robert', lastName: 'Langdon', role: 'WARDEN', isActive: true, phone: '+91 98765 22334', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-04', email: 'warden.girls@hms.edu', firstName: 'Sarah', lastName: 'Connor', role: 'WARDEN', isActive: true, phone: '+91 98765 33445', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-05', email: 'accountant@hms.edu', firstName: 'Arthur', lastName: 'Dent', role: 'ACCOUNTANT', isActive: true, phone: '+91 98765 44556', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-06', email: 'security@hms.edu', firstName: 'Marcus', lastName: 'Fenix', role: 'SECURITY', isActive: true, phone: '+91 98765 55667', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-07', email: 'mess@hms.edu', firstName: 'Gordon', lastName: 'Ramsay', role: 'MESS_STAFF', isActive: true, phone: '+91 98765 66778', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-08', email: 'maintenance@hms.edu', firstName: 'Bob', lastName: 'Builder', role: 'MAINTENANCE', isActive: true, phone: '+91 98765 77889', createdAt: '2023-01-01T00:00:00.000Z' },
  { id: 'user-09', email: 'student@hms.edu', firstName: 'Aarav', lastName: 'Sharma', role: 'STUDENT', isActive: true, phone: '+91 98765 88990', createdAt: '2023-08-01T00:00:00.000Z' },
  { id: 'user-10', email: 'parent@hms.edu', firstName: 'Rajesh', lastName: 'Sharma', role: 'PARENT', isActive: true, phone: '+91 98765 99001', createdAt: '2023-08-01T00:00:00.000Z' },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  { id: 'log-01', userEmail: 'superadmin@hms.edu', userRole: 'SUPER_ADMIN', action: 'ALLOCATION_CREATED', module: 'ALLOCATIONS', recordId: 'alloc-01', details: 'Allocated Room 101-A to Aarav Sharma', ipAddress: '192.168.1.10', createdAt: new Date().toISOString() },
  { id: 'log-02', userEmail: 'accountant@hms.edu', userRole: 'ACCOUNTANT', action: 'PAYMENT_RECORDED', module: 'FINANCE', recordId: 'pay-01', details: 'Recorded UPI payment of ₹59,000 for invoice HMS-REC-2026-001', ipAddress: '192.168.1.15', createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 'log-03', userEmail: 'warden.boys@hms.edu', userRole: 'WARDEN', action: 'GATEPASS_APPROVED', module: 'GATE_PASS', recordId: 'gp-01', details: 'Approved evening outing pass GP-2026-092', ipAddress: '192.168.1.20', createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 'log-04', userEmail: 'security@hms.edu', userRole: 'SECURITY', action: 'VISITOR_CHECKIN', module: 'VISITORS', recordId: 'vis-01', details: 'Checked in guardian Rajesh Sharma for student Aarav Sharma', ipAddress: '192.168.1.35', createdAt: new Date(Date.now() - 10800000).toISOString() },
];
